-- 코드를 작성해주세요

SELECT 
    C.ID, 
    C.GENOTYPE, 
    P.GENOTYPE AS PARENT_GENOTYPE 
FROM 
    ECOLI_DATA C
INNER JOIN 
    ECOLI_DATA P ON C.PARENT_ID = P.ID
WHERE
    (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID ASC


# 부모의 형질 => 현재 ID의 PARENT_ID로 조인하여 GENOTYPE를 찾음. 4 => 